### ISSUE TITLE
How to set my django project up with django-tenant-schemas docker and nginx

### ISSUE THREAD

**Issue by eduramofo** [bernardopires/django-tenant-schemas#535]
Hi everybody,

I am trying to set my project up with with docker, django-tenant-schemas and nginx. I am having a little struggle with "DisallowedHost at /
No tenant for "web".

It is a little hard to explain, so i will put all the config files bellow:

NOTE 1: When I set the project up without Docker it runs perfectly.

![img-3](https://user-images.githubusercontent.com/10105474/36990334-274da4a4-2083-11e8-944e-fceead8f28f4.png)

![img-1](https://user-images.githubusercontent.com/10105474/36990330-27087924-2083-11e8-8c34-29b35ad3f6e2.png)

![img-2](https://user-images.githubusercontent.com/10105474/36990331-272851fe-2083-11e8-985d-efc5d3ab6a87.png)

### Dockerfile
```
FROM python:3.6
ENV PYTHONUNBUFFERED 1
RUN mkdir /config
COPY /config/requirements.pip /config/
COPY /config/requirements-dev.pip /config/
RUN pip install -r /config/requirements-dev.pip
RUN mkdir /src;
WORKDIR /src
````

### docker-compose.yml
```
version: '2'

services:

  nginx:
    image: nginx:1.13
    container_name: azaper_nginx
    ports:
      - "80:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    container_name: azaper_app
    command: bash -c "python manage.py makemigrations && python manage.py migrate_schemas --shared && gunicorn azaper.wsgi -b 0.0.0.0:8000"
    volumes:
      - ./src:/src
    expose:
      - "8000"
````

#### config\nginx\azaper.conf
```
upstream web {
  ip_hash;
  server web:8000;
}

server {
  location / {
          proxy_pass http://web/;
    }
  listen 8000;
  server_name _;
}
```
